# Generated by Django 5.1.5 on 2025-01-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_email_verification_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_sent_at',
        ),
    ]
